version: "3.9"

services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/app

  nginx:
    image: nginx:1.25.3-alpine-slim
    ports:
      - 8000:80
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
    depends_on:
      - app
