version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/app

  nginx:
    image: nginx:1.25.3-alpine-slim
    ports:
      - 8000:80
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
    depends_on:
      - app

  db:
    env_file:
      - ./src/.env
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
      args:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
